### ISSUE TITLE
Comments in posts

### ISSUE THREAD

**Issue by perthsystem** [JustSteveKing/anchor-cms-llama-theme#1]
Hi,
I love the theme except that people can't add comments even though it is activated in admin.

Is there a way to fix this?

**Comment by tlongren** [comment]
I can fix this. I'll send you a pull request soon with a fix.

**Comment by tlongren** [comment]
https://github.com/JustSteveKing/anchor-cms-llama-theme/pull/2

Probably some styling issues as I haven't tested it yet.
